version: "3.9"
services:
  api:
    build:
      context: .
    image: jeter1226/fastapi_trello:1.0
    environment:
      TZ: Asia/Taipei
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - ./downloads:/app/downloads
    restart: on-failure
    ports:
      - 8002:8000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: