"""add position column to task model

Revision ID: 432e086d8e0f
Revises: ab2042e7230b
Create Date: 2025-05-09 16:04:30.610160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432e086d8e0f'
down_revision: Union[str, None] = 'ab2042e7230b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'position')
    # ### end Alembic commands ###
