"""Lanes model add position column

Revision ID: 4c565f371d04
Revises: 82a10d324441
Create Date: 2025-05-09 14:14:24.891486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c565f371d04'
down_revision: Union[str, None] = '82a10d324441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lanes', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lanes', 'position')
    # ### end Alembic commands ###
