"""update project mmodel description column type to nullable=True

Revision ID: d6fdc5ef6e32
Revises: 8848cee552f3
Create Date: 2025-03-27 15:51:45.757109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fdc5ef6e32'
down_revision: Union[str, None] = '8848cee552f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
